### ISSUE TITLE
Not a issue, but.... 

### ISSUE THREAD

**Issue by thrace19** [hansputera/tictactoe-game#1]
Anyways how are you hanif? I don't see you active on discord? Anything happened?

**Comment by hansputera** [comment]
Hello, I'm fine. How are you? I'm now moving to telegram, I'm not active on discord because telegram I think is more interesting than discord. A lot of the community is talking about things I can't find on discord.

**Comment by thrace19** [comment]
> Hello, I'm fine. How are you? I'm now moving to telegram, I'm not active on discord because telegram I think is more interesting than discord. A lot of the community is talking about things I can't find on discord.

I see. I just wanted to talk to a old friend that's it. It's good to see you're doing great 🙂

**Comment by hansputera** [comment]
> > Hello, I'm fine. How are you? I'm now moving to telegram, I'm not active on discord because telegram I think is more interesting than discord. A lot of the community is talking about things I can't find on discord.
> 
> I see. I just wanted to talk to a old friend that's it. It's good to see you're doing great 🙂

If you want to talk with me. It's my telegram username `@hanifdwyputra` 😄
